version: '3'

services:
  api:
    container_name: mackom-users-api
    build:
      args:
        EXPOSE_PORT: "${SERVICE_CONTAINER_PORT:-80}"
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../migrations:/migrations
    ports:
      - "${SERVICE_HOST_PORT:-80}:${SERVICE_CONTAINER_PORT:-80}"
    restart: "unless-stopped"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - mackom-users

  postgres:
    container_name: mackom-users-postgres
    image: postgres:15.6-alpine
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      SSL_MODE: ${SSL_MODE}
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - mackom-users

volumes:
  db-data:
    driver: local
networks:
  mackom-users:
